language: python
os:
  - linux
  - osx
  - windows
python:
  - "nightly"#
  - "3.8-dev"
  - "3.8"
  - "3.7"
  - "3.7-dev"
  - "3.6"
  - "3.6-dev"
  - "3.5"
  - "3.5-dev"
  - "3.4"
  - "3.4-dev"
install:
  - pip install -r requirements.txt
before_script: cd smvsite
script:
  - python manage.py migrate
  - python manage.py test