language: python
os:
  - linux
python:
  - "nightly"
  - "3.8-dev"
  - "3.8"
  - "3.7"
  - "3.7-dev"
  - "3.6"
  - "3.6-dev"
services:
  - postgresql
install:
  - pip install -r requirements.txt
env:
  global:
    - DEBUG=True
    - DB_ENGINE=django.db.backends.postgresql_psycopg2
    - DB_NAME=travis_ci_test
    - DB_USER=postgres
    - DB_PASSWORD=postgres
    - DB_HOST=localhost
    - DB_PORT=5432
before_script:
  - cd smvsite
  - psql -c 'create database travis_ci_test;' -U postgres
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - flake8
  - python manage.py migrate
  - python manage.py collectstatic
  - python manage.py test