# Generated by Django 3.1.1 on 2020-09-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komitee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Komitee',
        ),
    ]
