# Generated by Django 3.1.1 on 2020-09-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200921_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_post',
            field=models.BooleanField(default=True),
        ),
    ]
