# Generated by Django 3.1.2 on 2020-10-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_is_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
