# Generated by Django 3.1.2 on 2020-10-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201004_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_post',
            new_name='blogpost',
        ),
    ]
