# Generated by Django 3.1.1 on 2020-09-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Komitee',
        ),
    ]
