name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 # may be actions/checkout@v2 now
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag smvsite/smvsite:latest
      - name: Build the latest Docker image for static files
        run: docker build . --file Dockerfile.static --tag smvsite/static:latest
      - name: Push the latest Docker image
        run: docker push smvsite/smvsite:latest
      - name: Push the latest Docker image for static files
        run: docker push smvsite/static:latest
