name: Docker build test for pull-requests

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 # may be actions/checkout@v2 now
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag smvsite/smvsite:latest
